Update helper

diff --git a/src/helper/functions b/src/helper/functions
--- a/src/helper/functions
+++ b/src/helper/functions
@@ -15,7 +15,7 @@ function ensure_zwavejs_config {
 
 function get_network_key {
     if [ -f "${SNAP_DATA}/settings.json" ]; then
-        SETTINGS_KEY=$(jq '.zwave.networkKey' -r ${SNAP_DATA}/settings.json)
+        SETTINGS_KEY=$(jq '.zwave.networkKey' -r ${SN`AP_DATA}/settings.json)
         if [ "${SETTINGS_KEY}" != "" ] && [ "${1}" != "${SETTINGS_KEY}" ]; then
             echo "${SETTINGS_KEY}"
             return 1
@@ -60,7 +60,7 @@ function cpy_2_zui {
 			exit 1
 		fi
 	else
-		echo "Can not copy config: Missing connection «store-dir» (offered by <zwave-js-ui>: `snap install zwave-js-ui`)." >&2
+		echo "Can not copy config: Missing connection «store-dir» (offered by <zwave-js-ui>: 'snap install zwave-js-ui')." >&2
 		echo "Please install and connect with:" 1>&2
 		echo "$ snap connect ${SNAP_NAME}:zui-store zwave-js-ui:store-dir" >&2
 		return 1
